[package]
name = "cspr-sentinel-contract"
version = "0.1.0"
edition = "2021"

[dependencies]
casper-contract = { version = "3.0.0", default-features = false }
casper-types = "3.0.0"
wee_alloc = "0.4.5"

[[bin]]
name = "cspr_sentinel_contract"
path = "src/main.rs"

[profile.release]
codegen-units = 1
lto = true
opt-level = "z"
