export const CONFIG = {
  NETWORK_NAME: 'casper-test',
  CASPER_RPC_URL: process.env.CASPER_RPC_URL || 'https://rpc.testnet.casper.network/rpc',
  CASPER_EXPLORER_URL: 'https://testnet.cspr.live/deploy',
  CONTRACT_PACKAGE_NAME: 'cspr_sentinel_package_name',
  CONTRACT_HASH: process.env.CONTRACT_HASH || 'hash-0000000000000000000000000000000000000000000000000000000000000000',
  DEFAULT_BUDGET_POLICY: {
    maxPricePerRequestCspr: 0.5,
    maxSpendPerHourCspr: 5.0,
    autoApprove: true,
    paused: false,
  },
  MOTES_PER_CSPR: 1_000_000_000,
  MOCK_SERVICES: [
    {
      id: 'weather-oracle',
      name: 'Sentinel Weather Oracle',
      description: 'Real-time global atmospheric & climate data feed',
      category: 'Data Oracle',
      priceCspr: 0.1,
      priceMotes: '100000000',
      endpoint: '/services/weather-oracle',
      iconName: 'CloudSun',
    },
    {
      id: 'market-data-feed',
      name: 'Casper Market Depth Feed',
      description: 'Institutional level orderbook depth and volume metrics',
      category: 'Finance',
      priceCspr: 0.2,
      priceMotes: '200000000',
      endpoint: '/services/market-data-feed',
      iconName: 'TrendingUp',
    },
    {
      id: 'ai-inference-endpoint',
      name: 'Agentic Neural Inference API',
      description: 'Sub-second LLM inference & pattern detection vector query',
      category: 'AI / ML',
      priceCspr: 0.4,
      priceMotes: '400000000',
      endpoint: '/services/ai-inference-endpoint',
      iconName: 'Cpu',
    },
    {
      id: 'storage-pin-service',
      name: 'CSPR Immutable Storage Pin',
      description: 'Decentralized IPFS/Casper permanent document pinning',
      category: 'Storage',
      priceCspr: 0.3,
      priceMotes: '300000000',
      endpoint: '/services/storage-pin-service',
      iconName: 'Database',
    },
  ],
};
