export const CONFIG = {
  NETWORK_NAME: 'casper-test',
  CASPER_RPC_URL: process.env.CASPER_RPC_URL || 'https://rpc.testnet.casper.network/rpc',
  CASPER_EXPLORER_URL: 'https://testnet.cspr.live/deploy',
  CONTRACT_PACKAGE_NAME: 'cspr_sentinel_package_name',
  CONTRACT_HASH: process.env.CONTRACT_HASH || 'hash-0000000000000000000000000000000000000000000000000000000000000000',
  DEFAULT_BUDGET_POLICY: {
    maxPricePerRequestCspr: 0.5,
    maxSpendPerHourCspr: 5.0,
    autoApprove: true,
    paused: false,
  },
  MOTES_PER_CSPR: 1_000_000_000,
  MOCK_SERVICES: [
    {
      id: 'hash-verifier',
      name: 'Block Integrity Hash Verifier',
      description: 'Performs cryptographic chain validation and verification on Casper blocks',
      category: 'Network Auditing',
      priceCspr: 0.1,
      priceMotes: '100000000',
      endpoint: '/services/hash-verifier',
      iconName: 'Database',
    },
    {
      id: 'mempool-threat',
      name: 'Mempool Threat Detector',
      description: 'Scans the mempool for malicious deployment patterns and potential frontrunning vectors',
      category: 'Intrusion Detection',
      priceCspr: 0.2,
      priceMotes: '200000000',
      endpoint: '/services/mempool-threat',
      iconName: 'TrendingUp',
    },
    {
      id: 'node-security',
      name: 'Validator Node Security Monitor',
      description: 'Monitors validator logs and peer consensus behavior for malicious routing',
      category: 'Infrastructure',
      priceCspr: 0.3,
      priceMotes: '300000000',
      endpoint: '/services/node-security',
      iconName: 'ShieldAlert',
    },
    {
      id: 'contract-auditor',
      name: 'Autonomous Contract Auditor API',
      description: 'Sub-second vulnerability audit scan for Wasm smart contracts before deploy execution',
      category: 'Audit & Compliance',
      priceCspr: 0.4,
      priceMotes: '400000000',
      endpoint: '/services/contract-auditor',
      iconName: 'Cpu',
    },
  ],
};
